# Generated by Django 3.2.25 on 2024-10-03 20:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('suscripcion', models.BooleanField(default=False)),
                ('extension', models.CharField(blank=True, default='edu', max_length=5)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='colegios', to='academico.administrativo')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.colegio')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Primaria'), (2, 'Secundaria')])),
                ('grado', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ingrese un grado de 1ro a 6to'), django.core.validators.MinValueValidator(6, message='Ingrese un grado de 1ro a 6to')])),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('trimestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('ENT', 'Entregado'), ('PEN', 'Pendiante'), ('VEN', 'Vencido')], default='PEN', max_length=10)),
                ('calificacion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Elija una nota de 0 a 100'), django.core.validators.MaxValueValidator(100, message='Elija una nota de 0 a 100')])),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.curso')),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='tareas', through='academico.Revision', to='academico.Estudiante')),
                ('sesion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='core.session')),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.tarea'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='profesores', to='academico.colegio')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.colegio')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miercoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes')], max_length=5)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.grado'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_madre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='madre_estudiante', to='academico.padre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_padre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='padre_estudiante', to='academico.padre'),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=2000)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academico.revision')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(related_name='record', through='academico.Inscripcion', to='academico.Estudiante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='horarios',
            field=models.ManyToManyField(related_name='cursos_horario', to='academico.Horario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.periodo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cursos', to='academico.profesor'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(blank=True, choices=[('PEN', 'Pendiente'), ('ASI', 'Asistio'), ('FAL', 'Falta'), ('ATR', 'Atraso')], default='FAL', max_length=3)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.inscripcion')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.colegio'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.grado'),
        ),
    ]
