# Generated by Django 3.2.25 on 2024-10-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='user_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='madre_estudiante', to='academico.padre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='user_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='padre_estudiante', to='academico.padre'),
        ),
    ]
