# Generated by Django 3.2.25 on 2024-09-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='estado_tarea',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignaturaperiodo'),
        ),
        migrations.CreateModel(
            name='TareaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estadotarea')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignaturaestudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tarea')),
            ],
        ),
    ]
