# Generated by Django 3.2.25 on 2024-09-24 20:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0002_auto_20240908_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='asignaturaestudiante',
            name='asignatura_periodo',
        ),
        migrations.RemoveField(
            model_name='asignaturaestudiante',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='asignaturaperiodo',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='asignaturaperiodo',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='asignaturaperiodo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='asignatura_estudiante',
        ),
        migrations.DeleteModel(
            name='EstadoAsistencia',
        ),
        migrations.RemoveField(
            model_name='licencia',
            name='asistencia',
        ),
        migrations.RemoveField(
            model_name='licencia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='tareaestudiante',
            name='estado_tarea',
        ),
        migrations.RemoveField(
            model_name='tareaestudiante',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='tareaestudiante',
            name='tarea',
        ),
        migrations.RemoveField(
            model_name='grado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='grado',
            name='grado',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(1, message='Ingrese un grado de 1ro a 6to'), django.core.validators.MinValueValidator(6, message='Ingrese un grado de 1ro a 6to')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel',
            field=models.IntegerField(choices=[('1', 'Primaria'), ('2', 'Secundaria')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.grado'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AsignaturaEstudiante',
        ),
        migrations.DeleteModel(
            name='AsignaturaPeriodo',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='EstadoTarea',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Licencia',
        ),
        migrations.DeleteModel(
            name='Periodo',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='TareaEstudiante',
        ),
    ]
