# Generated by Django 3.2.25 on 2024-10-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_auto_20241003_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='sesion',
        ),
    ]
