# Generated by Django 3.2.25 on 2024-09-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20240924_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Primaria'), (2, 'Secundaria')]),
        ),
    ]
