# Generated by Django 3.2.25 on 2024-09-25 21:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('academico', '0004_alter_grado_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('colegio_e', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.colegio')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('trimestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('ENT', 'Entregado'), ('PEN', 'Pendiante'), ('VEN', 'Vencido')], default='PEN', max_length=10)),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Elija una nota de 0 a 100'), django.core.validators.MaxValueValidator(100, message='Elija una nota de 0 a 100')])),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(blank=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.curso')),
                ('estudiantes', models.ManyToManyField(related_name='tareas', through='academico.Revision', to='academico.Estudiante')),
                ('sesion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='core.session')),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.tarea'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('colegio_p', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.colegio')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=2000)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academico.revision')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(related_name='record', through='academico.Inscripcion', to='academico.Estudiante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.periodo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cursos', to='academico.profesor'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(blank=True, choices=[('ASI', 'Asistio'), ('FAL', 'Falta'), ('ATR', 'Atraso')], default='ATR', max_length=3)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.inscripcion')),
            ],
        ),
    ]
