# Generated by Django 3.2.25 on 2024-09-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20240925_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='colegio_e',
            new_name='colegio_p',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='caca',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
