# Generated by Django 3.2.25 on 2024-09-25 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0006_auto_20240925_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='institucion', to=settings.AUTH_USER_MODEL),
        ),
    ]
