# Generated by Django 3.2.25 on 2024-09-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_alter_colegio_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='colegio_p',
            new_name='colegio',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='colegio_p',
            new_name='colegio',
        ),
    ]
