# Generated by Django 3.2.25 on 2024-09-28 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('academico', '0008_auto_20240925_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='caca',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='colegio',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.RESTRICT, to='academico.colegio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='academico.grado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revision',
            name='calificacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Elija una nota de 0 a 100'), django.core.validators.MaxValueValidator(100, message='Elija una nota de 0 a 100')]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='tareas', through='academico.Revision', to='academico.Estudiante'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.colegio')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miercoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes')])),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='horarios',
            field=models.ManyToManyField(related_name='cursos_horario', to='academico.Horario'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_madre',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.RESTRICT, related_name='madre_estudiante', to='academico.padre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_padre',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='padre_estudiante', to='academico.padre'),
            preserve_default=False,
        ),
    ]
