# Generated by Django 3.2.25 on 2024-10-03 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('academico', '0009_auto_20240928_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='admin',
        ),
        migrations.AddField(
            model_name='colegio',
            name='suscripcion',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.colegio')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
    ]
