# Generated by Django 3.2.25 on 2024-10-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_auto_20241003_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='colegio',
        ),
    ]
