# Generated by Django 3.2.25 on 2024-10-03 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_remove_administrativo_colegio'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='academico.administrativo'),
            preserve_default=False,
        ),
    ]
