# Generated by Django 3.2.25 on 2024-10-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_colegio_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='extension',
            field=models.CharField(blank=True, default='edu', max_length=5),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='colegios', to='academico.administrativo'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='profesores', to='academico.colegio'),
        ),
    ]
